import {
  Bus,
  CalendarDays,
  Clock3,
  Hotel,
  Lightbulb,
  MapPin,
  Utensils,
} from "lucide-react";

import type { ItineraryDay } from "@/types/travel";

interface ItinerarySectionProps {
  itinerary: ItineraryDay[];
  currency: string;
}

// Show one activity: morning, afternoon, or evening.
function ActivityCard({
  time,
  title,
  description,
}: {
  time: string;
  title: string;
  description: string;
}) {
  return (
    <div className="rounded-xl border border-border bg-background p-4 dark:bg-[#1d2027]">
      <div className="flex items-start gap-3">

        <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-orange-50 text-accent dark:bg-orange-950/40">
          <Clock3 className="h-4 w-4" />
        </div>

        <div className="min-w-0">

          <p className="text-xs font-medium text-accent">
            {time}
          </p>

          <p className="mt-1 text-sm font-semibold text-foreground">
            {title}
          </p>

          <p className="mt-1 text-xs leading-5 text-muted-foreground">
            {description}
          </p>

        </div>
      </div>
    </div>
  );
}

export function ItinerarySection({
  itinerary,
  currency,
}: ItinerarySectionProps) {
  return (
    <section className="rounded-2xl border border-border bg-white p-5 shadow-sm dark:bg-[#191c22] sm:p-6">

      {/* Itinerary heading */}

      <div>

        <p className="text-xs font-medium uppercase tracking-[0.12em] text-accent">
          Your journey
        </p>

        <h2 className="mt-1 font-display text-2xl font-semibold text-foreground">
          Itinerary
        </h2>

        <p className="mt-1 text-sm text-muted-foreground">
          Your day-by-day plan generated by SmartTrip AI.
        </p>

      </div>


      {/* All trip days */}

      <div className="mt-6 space-y-5">

        {itinerary.map((day) => (

          <article
            key={day.day}
            className="overflow-hidden rounded-2xl border border-border"
          >

            {/* Day heading */}

            <div className="flex flex-col gap-3 bg-secondary/50 p-4 dark:bg-[#22262e] sm:flex-row sm:items-center sm:justify-between">

              <div className="flex items-center gap-3">

                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary text-sm font-bold text-primary-foreground">
                  {day.day}
                </div>

                <div>

                  <div className="flex items-center gap-2">

                    <CalendarDays className="h-4 w-4 text-accent" />

                    <h3 className="text-sm font-semibold text-foreground">
                      Day {day.day}
                    </h3>

                  </div>

                  <div className="mt-1 flex items-center gap-1.5">

                    <MapPin className="h-3.5 w-3.5 text-muted-foreground" />

                    <span className="text-xs text-muted-foreground">
                      {day.city}
                    </span>

                    <span className="text-xs text-muted-foreground">
                      •
                    </span>

                    <span className="text-xs text-muted-foreground">
                      {day.date}
                    </span>

                  </div>

                </div>

              </div>


              {/* Daily estimated cost */}

              <div className="w-fit rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-foreground shadow-sm dark:bg-[#191c22]">
                {currency}{" "}
                {day.estimated_daily_cost.toLocaleString("en-IN")}
              </div>

            </div>


            {/* Morning, afternoon and evening */}

            <div className="grid gap-3 bg-white p-4 dark:bg-[#191c22] sm:grid-cols-3">

              <ActivityCard
                time="Morning"
                title="Morning plan"
                description={day.morning}
              />

              <ActivityCard
                time="Afternoon"
                title="Afternoon plan"
                description={day.afternoon}
              />

              <ActivityCard
                time="Evening"
                title="Evening plan"
                description={day.evening}
              />

            </div>


            {/* Meals, transport and hotel */}

            <div className="grid gap-3 border-t border-border bg-secondary/20 p-4 dark:bg-[#15181e] sm:grid-cols-3">

              {/* Meals */}

              <div className="flex gap-3">

                <Utensils className="mt-0.5 h-4 w-4 shrink-0 text-accent" />

                <div>

                  <p className="text-xs font-medium text-foreground">
                    Meals
                  </p>

                  <div className="mt-1 space-y-0.5 text-xs leading-5 text-muted-foreground">

                    <p>
                      <span className="font-medium">
                        Breakfast:
                      </span>{" "}
                      {day.meals.breakfast}
                    </p>

                    <p>
                      <span className="font-medium">
                        Lunch:
                      </span>{" "}
                      {day.meals.lunch}
                    </p>

                    <p>
                      <span className="font-medium">
                        Dinner:
                      </span>{" "}
                      {day.meals.dinner}
                    </p>

                  </div>

                </div>

              </div>


              {/* Transport */}

              <div className="flex gap-3">

                <Bus className="mt-0.5 h-4 w-4 shrink-0 text-accent" />

                <div>

                  <p className="text-xs font-medium text-foreground">
                    Transport
                  </p>

                  <p className="mt-1 text-xs leading-5 text-muted-foreground">
                    {day.transport}
                  </p>

                </div>

              </div>


              {/* Hotel */}

              <div className="flex gap-3">

                <Hotel className="mt-0.5 h-4 w-4 shrink-0 text-accent" />

                <div>

                  <p className="text-xs font-medium text-foreground">
                    Stay
                  </p>

                  <p className="mt-1 text-xs leading-5 text-muted-foreground">
                    {day.hotel}
                  </p>

                </div>

              </div>

            </div>


            {/* Travel tips */}

            {day.tips.length > 0 && (

              <div className="border-t border-border px-4 py-3 dark:bg-[#191c22]">

                <div className="flex gap-2">

                  <Lightbulb className="mt-0.5 h-4 w-4 shrink-0 text-accent" />

                  <div>

                    <p className="text-xs font-medium text-foreground">
                      Travel tips
                    </p>

                    <ul className="mt-1 space-y-1">

                      {day.tips.map((tip, index) => (

                        <li
                          key={`${day.day}-tip-${index}`}
                          className="text-xs leading-5 text-muted-foreground"
                        >
                          • {tip}
                        </li>

                      ))}

                    </ul>

                  </div>

                </div>

              </div>

            )}

          </article>

        ))}

      </div>

    </section>
  );
}