import { ArrowLeft, Download, Sparkles } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useEffect, useState } from "react";

import { TripChatbot } from "@/components/trip/TripChatbot";

import { TripOverview } from "@/components/trip/TripOverview";
import { ItinerarySection } from "@/components/trip/ItinerarySection";
import { TransportSection } from "@/components/trip/TransportSection";
import { AccommodationSection } from "@/components/trip/AccommodationSection";
import { RestaurantSection } from "@/components/trip/RestaurantSection";
import { BudgetSection } from "@/components/trip/BudgetSection";
import { PackingSection } from "@/components/trip/PackingSection";

import {
  getTripById,
  type Trip,
} from "@/services/api/trip.service";

import type { TravelPlanOutput } from "@/services/api/itinerary.service";

export function TripDetailsPage() {
  const { tripId } = useParams();

  const [trip, setTrip] = useState<Trip | null>(null);

  const [travelPlan, setTravelPlan] =
    useState<TravelPlanOutput | null>(null);

  const [isLoading, setIsLoading] =
    useState(true);

  const [error, setError] =
    useState<string | null>(null);

  // Fetch the saved trip from Node backend
  useEffect(() => {
    const fetchTrip = async () => {
      if (!tripId) {
        setError("Trip ID is missing.");
        setIsLoading(false);
        return;
      }

      try {
        setIsLoading(true);
        setError(null);

        const response = await getTripById(
          Number(tripId),
        );

        const savedTrip = response.data.trip;

        setTrip(savedTrip);

        // The exact TravelPlanOutput generated by the LLM
        // was saved inside trip.travelPlan.
        if (savedTrip.travelPlan) {
          setTravelPlan(
            savedTrip.travelPlan as TravelPlanOutput,
          );
        } else {
          setError(
            "The saved trip does not contain an itinerary.",
          );
        }
      } catch (err) {
        console.error(
          "Failed to fetch saved trip:",
          err,
        );

        setError(
          "Unable to load this saved trip. Please try again.",
        );
      } finally {
        setIsLoading(false);
      }
    };

    fetchTrip();
  }, [tripId]);

  // Loading
  if (isLoading) {
    return (
      <main className="min-h-screen bg-[#f7f5f0] px-3 pb-24 pt-3 text-foreground dark:bg-[#111318] sm:px-5 sm:pt-4 lg:px-6">
        <div className="mx-auto max-w-7xl">
          <div className="flex min-h-[60vh] items-center justify-center">
            <div className="rounded-2xl border border-border bg-white px-8 py-10 text-center shadow-sm dark:bg-[#191c22]">
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-orange-50 text-accent">
                <Sparkles className="h-5 w-5 animate-pulse" />
              </div>

              <p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.12em] text-accent">
                SmartTrip AI
              </p>

              <h1 className="mt-2 font-display text-xl font-semibold">
                Loading your itinerary
              </h1>

              <p className="mt-2 text-sm text-muted-foreground">
                Fetching your saved travel plan.
              </p>
            </div>
          </div>
        </div>

        <TripChatbot />
      </main>
    );
  }

  // Error
  if (error || !trip || !travelPlan) {
    return (
      <main className="min-h-screen bg-[#f7f5f0] px-3 py-6 text-foreground dark:bg-[#111318] sm:px-5 lg:px-6">
        <div className="mx-auto max-w-2xl">
          <div className="rounded-2xl border border-border bg-white p-6 text-center shadow-sm dark:bg-[#191c22]">
            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-red-50 text-red-500">
              <Sparkles className="h-5 w-5" />
            </div>

            <p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.12em] text-accent">
              SmartTrip AI
            </p>

            <h1 className="mt-1 font-display text-xl font-semibold">
              Unable to load your trip
            </h1>

            <p className="mt-2 text-sm text-muted-foreground">
              {error ??
                "Something went wrong while loading your itinerary."}
            </p>

            <div className="mt-5">
              <Link
                to="/trips"
                className="inline-flex items-center gap-2 rounded-xl border border-border bg-white px-4 py-2 text-xs font-semibold transition hover:bg-secondary"
              >
                <ArrowLeft className="h-3.5 w-3.5" />
                Back to My Trips
              </Link>
            </div>
          </div>
        </div>
      </main>
    );
  }

  // Download / print
  const handleDownloadItinerary = () => {
    window.print();
  };

  return (
    <main className="min-h-screen bg-[#f7f5f0] px-3 pb-24 pt-3 text-foreground dark:bg-[#111318] sm:px-5 sm:pt-4 lg:px-6">
      <div className="mx-auto max-w-7xl">

        {/* ================= PAGE TOP ================= */}

        <header className="mb-3 flex items-center justify-between gap-3 print:hidden">
          <Link
            to="/trips"
            aria-label="Back to My Trips"
            className="
              flex
              h-8
              w-8
              shrink-0
              items-center
              justify-center
              rounded-lg
              border
              border-border
              bg-white
              text-muted-foreground
              transition
              hover:bg-secondary
              hover:text-foreground
              dark:bg-[#252932]
            "
          >
            <ArrowLeft className="h-3.5 w-3.5" />
          </Link>

          <div
            className="
              shrink-0
              rounded-full
              border
              border-border
              bg-white
              px-2.5
              py-1
              text-[10px]
              text-muted-foreground
              dark:bg-[#252932]
            "
          >
            Saved Trip #{trip.id}
          </div>
        </header>

        {/* ================= MAIN LAYOUT ================= */}

        <div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_285px]">

          {/* ================= LEFT SIDE ================= */}

          <div className="min-w-0 space-y-4">

            {/* Exact same Trip Overview */}
            <TripOverview
              summary={travelPlan.trip_summary}
            />

            {/* Saved trip message */}
            <div className="rounded-2xl border border-border bg-white px-5 py-4 text-center shadow-sm dark:bg-[#191c22]">
              <div className="flex items-center justify-center gap-1.5">
                <Sparkles className="h-3.5 w-3.5 text-accent" />

                <p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-accent">
                  SmartTrip AI
                </p>
              </div>

              <h1 className="mt-1 font-display text-xl font-semibold text-foreground sm:text-2xl">
                Your saved trip itinerary
              </h1>

              <p className="mt-1 text-xs text-muted-foreground">
                {travelPlan.itinerary.length} day
                {travelPlan.itinerary.length === 1
                  ? ""
                  : "s"} planned for your journey.
              </p>
            </div>

            {/* ================= ITINERARY ================= */}

            <ItinerarySection
              itinerary={travelPlan.itinerary}
              currency={travelPlan.budget.currency}
            />

            {/* ================= TRANSPORT ================= */}

            <TransportSection
              transport={travelPlan.transport}
            />

            {/* ================= ACCOMMODATION ================= */}

            <AccommodationSection
              accommodation={
                travelPlan.accommodation
              }
            />

            {/* ================= RESTAURANTS ================= */}

            <RestaurantSection
              restaurants={travelPlan.restaurants}
            />

            {/* ================= BUDGET ================= */}

            <BudgetSection
              budget={travelPlan.budget}
            />

            {/* ================= PACKING ================= */}

            <PackingSection
              packing={travelPlan.packing}
            />

            {/* ================= TRAVEL NOTES ================= */}

            {(travelPlan.important_notes.length > 0 ||
              travelPlan.limitations.length > 0) && (
              <section
                className="
                  rounded-xl
                  border
                  border-border
                  bg-white
                  p-4
                  shadow-sm
                  dark:bg-[#191c22]
                  sm:p-5
                "
              >
                <div>
                  <p className="text-[10px] font-medium uppercase tracking-[0.12em] text-accent">
                    Good to know
                  </p>

                  <h2 className="mt-1 font-display text-lg font-semibold text-foreground">
                    Travel notes
                  </h2>
                </div>

                {/* Important notes */}

                {travelPlan.important_notes.length > 0 && (
                  <div className="mt-3">
                    <h3 className="text-xs font-semibold text-foreground">
                      Important notes
                    </h3>

                    <ul className="mt-1.5 space-y-1">
                      {travelPlan.important_notes.map(
                        (note, index) => (
                          <li
                            key={`note-${index}`}
                            className="text-[11px] leading-4 text-muted-foreground"
                          >
                            • {note}
                          </li>
                        ),
                      )}
                    </ul>
                  </div>
                )}

                {/* Limitations */}

                {travelPlan.limitations.length > 0 && (
                  <div className="mt-3 border-t border-border pt-3">
                    <h3 className="text-xs font-semibold text-foreground">
                      Planning limitations
                    </h3>

                    <ul className="mt-1.5 space-y-1">
                      {travelPlan.limitations.map(
                        (limitation, index) => (
                          <li
                            key={`limitation-${index}`}
                            className="text-[11px] leading-4 text-muted-foreground"
                          >
                            • {limitation}
                          </li>
                        ),
                      )}
                    </ul>
                  </div>
                )}
              </section>
            )}
          </div>

          {/* ================= RIGHT SIDE ================= */}

          <aside
            className="
              lg:sticky
              lg:top-4
              print:hidden
            "
          >
            {/* No AgentProgress here.
                This trip has already been generated. */}
          </aside>
        </div>
      </div>

      {/* Chatbot */}
      <TripChatbot />

      {/* ================= DOWNLOAD BAR ================= */}

      <div
        className="
          fixed
          bottom-4
          left-1/2
          z-40
          -translate-x-1/2
          print:hidden
        "
      >
        <div
          className="
            flex
            items-center
            gap-2
            rounded-2xl
            border
            border-white/80
            bg-white/90
            p-2
            shadow-[0_12px_40px_rgba(0,0,0,0.16)]
            backdrop-blur-xl
            dark:border-white/10
            dark:bg-[#1b1e25]/95
          "
        >
          <button
            type="button"
            onClick={handleDownloadItinerary}
            className="
              flex
              h-9
              items-center
              justify-center
              gap-1.5
              rounded-xl
              bg-primary
              px-4
              text-[11px]
              font-semibold
              text-primary-foreground
              transition
              hover:opacity-90
              sm:text-xs
            "
          >
            <Download className="h-3.5 w-3.5" />

            <span>
              Download Itinerary
            </span>
          </button>
        </div>
      </div>

      {/* ================= PRINT STYLES ================= */}

      <style>{`
        @media print {
          body {
            background: white !important;
          }

          main {
            padding: 0 !important;
            background: white !important;
          }

          header,
          aside,
          [class*="fixed"] {
            display: none !important;
          }

          section {
            break-inside: avoid;
            box-shadow: none !important;
          }

          img {
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
          }

          @page {
            margin: 12mm;
          }
        }
      `}</style>
    </main>
  );
}